mlx4: Add missing header file
On Nvidia jetson system we get the error below, this patch fixing
the issue.

error: implicit declaration of function ‘proc_mkdir’; did you mean
‘vfs_mkdir’? [-Werror=implicit-function-declaration]
  mlx4_core_proc_dir = proc_mkdir(MLX4_CORE_PROC, NULL);

issue: 1759281
Change-Id: I51f8e91747200d1963821aa097aa3cb56dc95837
Signed-off-by: Talat Batheesh <talatb@mellanox.com>