net/mlx5: Fix tracer frame size compilation error
This change fixes the following compilation warning:
drivers/net/ethernet/mellanox/mlx5/core/diag/fw_tracer.c: In
function 'mlx5_tracer_print_trace.isra.9':
drivers/net/ethernet/mellanox/mlx5/core/diag/fw_tracer.c:592:1:
warning: the frame size of 1032 bytes is larger than 1024 bytes
[-Wframe-larger-than=]

This warning indicates that the size of the function is bigger
that 1024, it happens since the function's variables size exceeds
the max size of the stack frame.

Issue: 1574703
Change-Id: I3f19eb80d26bf96ccdd9cfdc71a943920f95b522
Signed-off-by: Feras Daoud <ferasda@mellanox.com>